apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-config
data:
  ACCEPT_EULA: "Y"

# This sets environment variables required by the SQL Server Docker image.

# ACCEPT_EULA=Y means you accept Microsoft’s SQL Server license agreement.

# We separate this into a ConfigMap for clean separation of config and to allow reusability/modifiability 
# without touching the container spec.
