apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        resources:
          requests:
            memory: "2Gi" # Increase the requested memory
            cpu: "500m"
          limits:
            memory: "4Gi" # Increase the memory limit
            cpu: "1"
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD
        envFrom:
        - configMapRef:
            name: mssql-config
        volumeMounts:
        - name: mssql-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-storage
        persistentVolumeClaim:
          claimName: mssql-data

# Deploys the official SQL Server 2022 image from Microsoft.

# Mounts environment variables from the ConfigMap and Secret.

# Maps /var/opt/mssql (default DB path) to the persistent volume.

# Exposes container port 1433 (default SQL port).

# replicas: 1 since SQL Server doesn’t support active-active clustering out-of-the-box.
