apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

# SQL Server stores its database files inside the container at /var/opt/mssql.

# To persist data even if the pod is deleted or restarted, we use a PersistentVolumeClaim (PVC).

# This PVC requests 8 GB of storage with ReadWriteOnce access (only one pod can write at a time).
