apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
type: Opaque
data:
  SA_PASSWORD: TG9uZ3dheTJmYWxsQDc4MzQ3

# SQL Server requires a strong system admin password (SA_PASSWORD).

# This password is stored securely in a Kubernetes Secret, so it’s not hardcoded in your Deployment.

# stringData is a more human-readable way to input values; Kubernetes encodes it automatically.
