apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  type: NodePort
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: sqlserver

# A Kubernetes Service exposes the SQL Server pod.

# type: NodePort opens port 31433 on the Kubernetes node, mapping to port 1433 on the pod.

# You can connect from your local machine using: <NodeIP>:31433
