services:
  bookingservice:
    image: ${DOCKER_REGISTRY-}bookingservice
    build:
      context: .
      dockerfile: Services/BookingService/Dockerfile

  paymentservice:
    image: ${DOCKER_REGISTRY-}paymentservice
    build:
      context: .
      dockerfile: Services/PaymentService/Dockerfile

