global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "bookingService"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["host.docker.internal:8081"]
