apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingservice
spec:
  selector:
    matchLabels:
      app: bookingservice
  template:
    metadata:
      labels:
        app: bookingservice
    spec:
      containers:
      - name: bookingservice-host
        image: bookingservice
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: OTEL_SERVICE_NAME
          value: BookingService
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-data
